### ISSUE TITLE
Include UID as a copyable element in the popup

### ISSUE THREAD

**Issue by markjulmar** [patridge/learn-metadata-tool#27] opened 2020-06-05 22:43 UTC
I find that I am constantly having to jump to the YAML to pull the UID for the module/path. I'd love to just have UID in the popup with a copy button so I don't have to go to the YAML to get it.

**Comment by patridge** [comment] 2020-06-08 14:16
(Closing as duplicate of #21)
Thank you for letting me know, and I totally agree. I have that in my queue for the next revision.

At some point, I want to allow for user customization of that like I have started offering in the [GitHub Pull Request Minimizer extension](https://github.com/patridge/github-pull-request-minimizer#customize-with-your-own-bot-name-prefixes).

**Closed as completed by patridge** 2020-06-08 14:16 UTC
